# Generated by ChatGPT on 2026-01-29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("portal", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="answer",
            name="text",
            field=models.CharField(blank=True, max_length=1500),
        ),
    ]
