# Generated by ChatGPT on 2026-01-29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("portal", "0002_alter_answer_text"),
    ]

    operations = [
        migrations.AddField(
            model_name="chapter",
            name="culoare",
            field=models.CharField(
                blank=True,
                default="#0b3d91",
                help_text="Cod culoare HEX, de ex. #0B3D91 (folosit în interfață).",
                max_length=7,
            ),
        ),
        migrations.AddField(
            model_name="criterion",
            name="culoare",
            field=models.CharField(
                blank=True,
                default="#0b3d91",
                help_text="Cod culoare HEX, de ex. #0B3D91 (folosit în interfață).",
                max_length=7,
            ),
        ),
    ]
