# Generated by ChatGPT on 2026-01-30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("portal", "0003_add_culoare_to_refs"),
    ]

    operations = [
        migrations.AddField(
            model_name="cluster",
            name="culoare",
            field=models.CharField(
                max_length=7,
                blank=True,
                default="#0b3d91",
                help_text="Cod culoare HEX, de ex. #0B3D91 (folosit în interfață).",
            ),
        ),
    ]
