# Generated by ChatGPT on 2026-03-16

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("portal", "0014_pna_projects"),
    ]

    operations = [
        migrations.CreateModel(
            name="PnaInstitution",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("nume", models.CharField(max_length=400, unique=True)),
                ("creat_la", models.DateTimeField(auto_now_add=True)),
                ("actualizat_la", models.DateTimeField(auto_now=True)),
            ],
            options={
                "verbose_name": "Instituție PNA",
                "verbose_name_plural": "Instituții PNA",
                "ordering": ["nume"],
            },
        ),
        migrations.AddField(
            model_name="pnaproject",
            name="institutie_principala_ref",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="proiecte_principale",
                to="portal.pnainstitution",
            ),
        ),
        migrations.AddField(
            model_name="pnaproject",
            name="institutii_responsabile",
            field=models.ManyToManyField(
                blank=True,
                related_name="proiecte_responsabile",
                to="portal.pnainstitution",
            ),
        ),
        migrations.AddField(
            model_name="pnaproject",
            name="status_implementare",
            field=models.CharField(
                choices=[
                    ("NEINCEPUT", "Neînceput"),
                    ("IN_LUCRU_GUVERN", "În lucru la Guvern"),
                    ("IN_AVIZARE_GUVERN", "În avizare la Guvern"),
                    ("ADOPTAT_GUVERN", "Adoptat de Guvern"),
                    ("IN_AVIZARE_CE", "În avizare la Comisia Europeană"),
                    (
                        "IN_PROCEDURA_PARLAMENT",
                        "În procedură legislativă la Parlament",
                    ),
                    ("ADOPTAT_PARLAMENT", "Adoptat de Parlament"),
                ],
                default="NEINCEPUT",
                max_length=40,
            ),
        ),
        migrations.AddField(
            model_name="pnaproject",
            name="raport_extindere_2023",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="pnaproject",
            name="raport_extindere_2024",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="pnaproject",
            name="raport_extindere_2025",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="pnaproject",
            name="raport_extindere_2026",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="pnaproject",
            name="raport_extindere_2027",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="pnaproject",
            name="plan_crestere_economica",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="pnaproject",
            name="necesita_avizare_comisia_europeana",
            field=models.BooleanField(default=False),
        ),
    ]
