# Generated by ChatGPT on 2026-03-16

from django.db import migrations


INSTITUTIONS_RAW = """
AAC – Autoritatea Aeronautică Civilă
AAD – Agenția Națională Arheologică
AAP – Agenția Achiziții Publice
ACI – Agenția Națională pentru Cercetare și Inovare
Agenția Geodezie, Cartografie și Cadastru
Agenția Moldsilva
Agenția „Moldsilva”
Agenția pentru Securitatea Alimentelor
Agenția Proprietății Publice
Agenția Relații Interetnice
AIPA - Agenția de Intervenție și Plăți pentru Agricultură
AITT - Agenția de Investiții și Transfer Tehnologic
AMDM - Agenția Medicamentului și Dispozitivelor Medicale
ANACEC - Agenția Națională de Asigurare a Calității în Educație și Cercetare
ANAP - Agenția Națională Antidoping
ANPC – Agenția Națională pentru Cercetare și Inovare
ANRE - Agenția Națională pentru Reglementare în Energetică
ANSA – Agenția Națională pentru Siguranța Alimentelor
ANT – Agenția Națională pentru Tineret
ASP – Agenția Servicii Publice
Autoritatea Aeronautică Civilă
Autoritatea Națională de Integritate
Autoritatea Vamală
Banca Națională a Moldovei
Biroul Național de Statistică
Biroul Relații cu Veteranii
Biroul politici de reintegrare
CNA - Centrul Național Anticorupție
CNC - Centrul Național al Cinematografiei
CNCD – Consiliul Național pentru Combaterea Discriminării
CNEAS - Consiliul Național pentru Evaluare și Acreditare în Sănătate
CNPF – Comisia Națională a Pieței Financiare
CNPDCP - Centrul Național pentru Protecția Datelor cu Caracter Personal
CNSM - Comisia Națională a Securității Moldova
Consiliul Audiovizualului
Consiliul Concurenței
Consiliul Național pentru Acces la Informații
Consiliul Național pentru Asistență Juridică Garantată de Stat
Consiliul Național pentru Combaterea Discriminării și Asigurarea Egalității
Consiliul Național pentru Evaluare și Acreditare în Sănătate
Consiliul Superior al Magistraturii
Consiliul Superior al Procurorilor
Curtea de Conturi
Curtea Constituțională
CSM
Centrul de Armonizare a Legislației
Centrul de Instruire a Avocaților
Centrul Național pentru Energie Durabilă (CNED)
Centrul Național pentru Protecția Datelor cu Caracter Personal
Centrul Național pentru Transparență și Integritate
Centrul Național de Prevenire și Combatere a Spălării Banilor
Comisia Electorală Centrală
Comisia Națională pentru Consultări și Negocieri Colective
Comisia Națională pentru Examinarea Investițiilor de Importanță pentru Securitatea Statului
Comisia Națională pentru Sănătate Publică
Comisia Națională a Pieței Financiare
Departamentul Instituții Penitenciare
Departamentul pentru Eficiență Energetică
Direcția Generală pentru Protecția Drepturilor Copilului
DSE - Departamentul Situații Excepționale
Energocom
Fondul Național de Asigurări Sociale
IES - Inspectoratul de Stat al Muncii
Inspectoratul General al Poliției
Inspectoratul General al Poliției de Frontieră
Inspectoratul General pentru Migrație
Inspectoratul General pentru Situații de Urgență
Inspectoratul General pentru Situații de Urgență (IGSU)
Inspectoratul de Stat pentru Supravegherea Tehnică
Inspectoratul pentru Protecția Mediului
Inspecția Financiară
INJ - Institutul Național al Justiției
INSP - Institutul Național de Sănătate Publică
Institutul Național de Cercetări Economice
Institutul Național de Standardizare
Institutul Național de Metrologie
Institutul de Medicină Urgentă
ISSP - Instituția Publică Ingineria Sistemelor și Securitatea Informației
MAE – Ministerul Afacerilor Externe
MAEIE – Ministerul Afacerilor Externe și Integrării Europene
MAIA - Ministerul Agriculturii și Industriei Alimentare
MAI – Ministerul Afacerilor Interne
MCC - Ministerul Culturii
MDED - Ministerul Dezvoltării Economice și Digitalizării
MEC - Ministerul Educației și Cercetării
MEn - Ministerul Energiei
MF - Ministerul Finanțelor
MIn - Ministerul Infrastructurii
MIDR – Ministerul Infrastructurii și Dezvoltării Regionale
MJ - Ministerul Justiției
MM - Ministerul Mediului
MS - Ministerul Sănătății
MSMPS - Ministerul Muncii și Protecției Sociale
MT - Ministerul Transporturilor
Ministerul Transporturilor și Infrastructurii Drumurilor
Oficiul Avocatului Poporului
Oficiul Național de Dezvoltare Regională și Locală
Oficiul Național de Prevenire și Combatere a Spălării Banilor
Oficiul Național pentru Jocuri de Noroc
Oficiul Național pentru Protecția Consumatorilor
Oficiul Național pentru Protecția Consumatorilor și Supravegherea Pieței
Oficiul Național pentru Protecția Drepturilor de Autor
Oficiul Național pentru Protecția Drepturilor Omului
Oficiul Național pentru Protecția Mediului
Oficiul Național pentru Reglementare în Comunicații Electronice și Tehnologia Informației (ANRCETI)
Oficiul Național pentru Reglementare în Comunicații Electronice și Tehnologia Informației
Oficiul Național pentru Supraveghere Tehnică
Parlamentul Republicii Moldova
Procuratura Generală
Serviciul Fiscal de Stat
Serviciul Tehnologia Informației și Securitate Cibernetică
Serviciul Tehnologia Informației și Securitate Cibernetică (STISC)
Serviciul de Informații și Securitate
Serviciul Prevenirea și Combaterea Spălării Banilor
Serviciul Protecției și Pazei de Stat
Serviciul Vamal
Serviciul de Stat pentru Verificare și Control
Serviciul de Stat pentru Controlul Armelor
Serviciul de Stat pentru Controlul și Supravegherea Pieței
Serviciul de Stat pentru Controlul și Supravegherea Pieței și Protecția Consumatorilor
Serviciul de Stat pentru Protecția Consumatorilor
Serviciul de Stat pentru Protecția Consumatorilor și Supravegherea Pieței
Serviciul de Stat pentru Protecția Drepturilor Omului
Serviciul de Stat pentru Protecția Drepturilor Omului și Libertăților Fundamentale
Serviciul de Stat pentru Protecția Drepturilor de Autor
Serviciul de Stat pentru Protecția Mediului
Serviciul de Stat pentru Reglementare în Comunicații Electronice
Serviciul de Stat pentru Reglementare în Comunicații Electronice și Tehnologia Informației
Serviciul de Stat pentru Reglementare în Comunicații Electronice și Tehnologia Informației (ANRCETI)
Serviciul de Stat pentru Reglementare în Energetică
Serviciul de Stat pentru Reglementare în Energetică (ANRE)
Serviciul de Stat pentru Securitatea Alimentelor
Serviciul de Stat pentru Supravegherea Tehnică
Serviciul de Stat pentru Supravegherea Tehnică (ONST)
Serviciul de Stat pentru Supravegherea Transporturilor
Serviciul de Stat pentru Supravegherea Transporturilor și Siguranța Circulației
Serviciul de Stat pentru Supravegherea Transporturilor și Siguranța Circulației Rutiere
Serviciul de Stat pentru Supravegherea Transporturilor și Siguranța Circulației Rutiere
SPCSB - Serviciul Prevenirea și Combaterea Spălării Banilor
STS - Serviciul Tehnologia Securității
Unitatea Consolidată pentru Implementarea și Monitorizarea Programelor în Domeniul Sănătății
UPU - Unitatea de Implementare a Proiectelor în Energetică
"""


def seed_institutions(apps, schema_editor):
    PnaInstitution = apps.get_model("portal", "PnaInstitution")

    seen = set()
    for line in INSTITUTIONS_RAW.splitlines():
        name = (line or "").strip()
        if not name:
            continue
        # linie incompletă / inutilă
        if name in {"MAI –", "MAI -"}:
            continue
        if name in seen:
            continue
        seen.add(name)
        PnaInstitution.objects.get_or_create(nume=name)


def unseed_institutions(apps, schema_editor):
    # NU ștergem în rollback (poate exista referințe în proiecte).
    pass


class Migration(migrations.Migration):

    dependencies = [
        ("portal", "0015_pna_institutions_and_status"),
    ]

    operations = [
        migrations.RunPython(seed_institutions, unseed_institutions),
    ]
