# Generated by ChatGPT on 2026-03-16

import re

from django.db import migrations


def _norm(s: str) -> str:
    s0 = (s or "").strip()
    s0 = s0.replace("—", "-").replace("–", "-")
    s0 = re.sub(r"\s+", " ", s0)
    return s0


def backfill_projects(apps, schema_editor):
    PnaProject = apps.get_model("portal", "PnaProject")
    PnaInstitution = apps.get_model("portal", "PnaInstitution")

    # map by normalized lowercase
    inst_map = {(_norm(i.nume).lower()): i for i in PnaInstitution.objects.all()}

    def get_inst(name: str):
        name0 = _norm(name)
        if not name0:
            return None
        key = name0.lower()
        obj = inst_map.get(key)
        if obj:
            return obj
        obj, _ = PnaInstitution.objects.get_or_create(nume=name0[:400])
        inst_map[key] = obj
        return obj

    for p in PnaProject.objects.all().iterator():
        # principal
        if not getattr(p, "institutie_principala_ref_id", None):
            principal_txt = _norm(getattr(p, "institutie_principala", ""))
            if principal_txt:
                inst = get_inst(principal_txt)
                if inst:
                    p.institutie_principala_ref_id = inst.id
                    p.save(update_fields=["institutie_principala_ref"])

        # responsabile (doar dacă nu există deja)
        try:
            has_m2m = p.institutii_responsabile.exists()
        except Exception:
            has_m2m = True

        if not has_m2m:
            other_txt = _norm(getattr(p, "institutie_coreponsabila", ""))
            if other_txt:
                parts = [
                    _norm(x)
                    for x in re.split(r"[;,/\n]+", other_txt)
                    if x and _norm(x)
                ]
                seen = set()
                others = []
                principal_id = getattr(p, "institutie_principala_ref_id", None)
                for nm in parts:
                    key = nm.lower()
                    if key in seen:
                        continue
                    seen.add(key)
                    inst = get_inst(nm)
                    if inst and inst.id != principal_id:
                        others.append(inst)
                if others:
                    p.institutii_responsabile.set(others)


def noop(apps, schema_editor):
    pass


class Migration(migrations.Migration):

    dependencies = [
        ("portal", "0016_seed_pna_institutions"),
    ]

    operations = [
        migrations.RunPython(backfill_projects, noop),
    ]
