# Generated by Django 5.2.13 on 2026-04-10 11:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portal', '0024_expert_dashboard_seen'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='criterion',
            options={'ordering': ['cod'], 'verbose_name': 'Foaie de parcurs', 'verbose_name_plural': 'Foi de parcurs'},
        ),
        migrations.AlterField(
            model_name='importrun',
            name='kind',
            field=models.CharField(choices=[('EXPERTI', 'Import experți'), ('CHESTIONARE', 'Import chestionare'), ('PNA', 'Import PNA')], default='EXPERTI', max_length=20),
        ),
    ]
